In [2]:
import pandas as pd 

df = pd.read_csv("microsoft.csv")

In [43]:
df.iloc(1)

In [40]:
print(df)

                          Date        Open        High         Low  \
0    2025-03-17 00:00:00-04:00  383.762112  389.726432  382.640693
1    2025-03-18 00:00:00-04:00  384.129279  384.426988  378.204634
2    2025-03-19 00:00:00-04:00  382.600955  386.719420  381.082581
3    2025-03-20 00:00:00-04:00  382.809352  388.813406  380.368050
4    2025-03-21 00:00:00-04:00  380.308520  388.763779  379.891697
..                         ...         ...         ...         ...
246  2026-03-10 00:00:00-04:00  410.029999  410.200012  402.929993
247  2026-03-11 00:00:00-04:00  405.570007  409.010010  401.589996
248  2026-03-12 00:00:00-04:00  404.630005  406.119995  401.709991
249  2026-03-13 00:00:00-04:00  401.000000  404.799988  394.250000
250  2026-03-16 00:00:00-04:00  397.945007  400.630005  394.790009

          Close    Volume  Dividends  Stock Splits  Daily Change
0    385.746918  22474300        0.0           0.0           NaN
1    380.606232  19486900        0.0           0.0     -3.155881
2    384.873566  19185500        0.0           0.0      0.744287
3    383.901001  18470500        0.0           0.0      1.300046
4    388.287445  39675900        0.0           0.0      5.478093
..          ...       ...        ...           ...           ...
246  405.760010  31706400        0.0           0.0      0.839996
247  404.880005  25512100        0.0           0.0     -5.149994
248  401.859985  27263900        0.0           0.0     -3.710022
249  395.549988  26808000        0.0           0.0     -9.080017
250  399.950012  27676508        0.0           0.0     -1.049988

[251 rows x 9 columns]

In [34]:
close_prices = df["Close"]

In [37]:
df["Daily Change"] = df["Close"] - df["Open"].shift(1)

In [21]:
df[df["Close"] > 500]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
78,2025-07-09 00:00:00-04:00,497.410477,503.853062,496.853714,500.601959,18659500,0.0,0.0
80,2025-07-11 00:00:00-04:00,495.591061,502.113171,494.924917,500.413055,16459500,0.0,0.0
81,2025-07-14 00:00:00-04:00,498.623440,501.059302,498.136280,500.114777,12058800,0.0,0.0
82,2025-07-15 00:00:00-04:00,500.114774,505.364278,499.886122,502.898621,14927200,0.0,0.0
83,2025-07-16 00:00:00-04:00,502.262307,503.793421,498.991330,502.699768,15154400,0.0,0.0
...,...,...,...,...,...,...,...,...
166,2025-11-11 00:00:00-05:00,502.709549,507.489690,500.269713,506.573486,17980000,0.0,0.0
167,2025-11-12 00:00:00-05:00,507.250657,509.551119,497.053072,509.023315,26574900,0.0,0.0
168,2025-11-13 00:00:00-05:00,508.196729,511.373521,499.214093,501.205811,25273100,0.0,0.0
169,2025-11-14 00:00:00-05:00,496.166796,509.481424,495.380058,508.067291,28505700,0.0,0.0
170,2025-11-17 00:00:00-05:00,506.344474,509.999259,502.819125,505.388428,19092800,0.0,0.0

In [23]:
df[(df["Close"] > 500) | (df["Open"] > 500)]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
78,2025-07-09 00:00:00-04:00,497.410477,503.853062,496.853714,500.601959,18659500,0.0,0.0
79,2025-07-10 00:00:00-04:00,500.144588,501.526575,494.875211,498.583679,16492100,0.0,0.0
80,2025-07-11 00:00:00-04:00,495.591061,502.113171,494.924917,500.413055,16459500,0.0,0.0
81,2025-07-14 00:00:00-04:00,498.623440,501.059302,498.136280,500.114777,12058800,0.0,0.0
82,2025-07-15 00:00:00-04:00,500.114774,505.364278,499.886122,502.898621,14927200,0.0,0.0
...,...,...,...,...,...,...,...,...
166,2025-11-11 00:00:00-05:00,502.709549,507.489690,500.269713,506.573486,17980000,0.0,0.0
167,2025-11-12 00:00:00-05:00,507.250657,509.551119,497.053072,509.023315,26574900,0.0,0.0
168,2025-11-13 00:00:00-05:00,508.196729,511.373521,499.214093,501.205811,25273100,0.0,0.0
169,2025-11-14 00:00:00-05:00,496.166796,509.481424,495.380058,508.067291,28505700,0.0,0.0
170,2025-11-17 00:00:00-05:00,506.344474,509.999259,502.819125,505.388428,19092800,0.0,0.0

In [58]:
print(df.index)

RangeIndex(start=0, stop=251, step=1)

In [32]:
df.loc[df["Dividends"] > 0, "Stock Splits"] = 0

In [33]:
df.loc[df["Dividends"] > 0]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
42,2025-05-15 00:00:00-04:00,448.166524,453.555233,447.828491,450.512909,21992300,0.83,0.0
109,2025-08-21 00:00:00-04:00,501.604145,505.527832,500.638161,502.151855,18443300,0.83,0.0
173,2025-11-20 00:00:00-05:00,491.587964,492.446022,474.417164,477.340485,26802500,0.91,0.0
233,2026-02-19 00:00:00-05:00,400.690002,404.429993,396.670013,398.459991,28234000,0.91,0.0

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px

In [45]:

df = pd.read_csv("microsoft.csv")

In [46]:
print(df.head())

                        Date        Open        High         Low       Close  \
0  2025-03-17 00:00:00-04:00  383.762112  389.726432  382.640693  385.746918
1  2025-03-18 00:00:00-04:00  384.129279  384.426988  378.204634  380.606232
2  2025-03-19 00:00:00-04:00  382.600955  386.719420  381.082581  384.873566
3  2025-03-20 00:00:00-04:00  382.809352  388.813406  380.368050  383.901001
4  2025-03-21 00:00:00-04:00  380.308520  388.763779  379.891697  388.287445

     Volume  Dividends  Stock Splits
0  22474300        0.0           0.0
1  19486900        0.0           0.0
2  19185500        0.0           0.0
3  18470500        0.0           0.0
4  39675900        0.0           0.0

In [56]:
px.bar(df, x="Date", y="Close", color = "Close", color_discrete_sequence=["red, blue, green, yellow"] )